version: '3'
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./web.template:/etc/nginx/conf.d/web.template
      - ./build.sh:/build.sh
    working_dir: /
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=web.io
      - NGINX_PORT=80
    entrypoint: ./build.sh
    networks:
      - web
networks:
  web:
    external: true
    