version: '3'
services:
  redisCommander:
    container_name: redisCommander
    image: tenstartups/redis-commander
    command: --redis-host redis
    ports:
      - "8081:8081"
    networks:
      - default
      - database
  adminmongo:
    container_name: adminmongo
    build: ./adminmongo
    entrypoint: ./build.sh
    working_dir: /
    volumes:
      - ./adminmongo/build.sh:/build.sh
      - ./adminmongo/app.json:/app.json
    restart: always
    ports:
      - 8082:8082
    environment:
      - HOST=0.0.0.0
      - PORT=8082
      - LOCALE=en
      - CONN_NAME=localhost
      - DB_HOST=mongodb
      - DB_PORT=27017
    networks:
      - default
      - database
networks:
  database:
    external: true